slic-segments : 1200
slic-compactness: 20
n-ori : 8
k-mean-num : 64
sigma-sm : 2.0
sigma-lg : 2.83

daisy-step : 1
daisy-radius : 58
daisy-rings : 2
daisy-histograms : 6
daisy-orientations : 8
hist-bins-daisy : 64

codebook-size: 256
kmeans-thresh: 0.0001
kmeans-n-samples: 2000

hist-bins-color : 10
hist-bins-texture : 64
initial-saliency : 1.0
saliency-bias : 1.0

n-trees: 255
sample-size-ratio: 0.7

n-classifiers: 10
